services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3048
    ports:
      - "0.0.0.0:3048:3048"
    restart: always
